# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de26d9d0ec83231d94457af6b5e3d1b1a46649143ed9a7b86eabad215860b13dd80bf34d73c98f92bc68cb6cea54aa53f3ddaac2d5a9430b6c0f1072554876ab

test:
  secret_key_base: e61cefa94d0f86c25b482c2db29c3e622e97e34a56b821cb1ac535ff4971fdabdfe178527023de9ecb2e79b90ff5ec447128ab494403942f64a3670ea715dda3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
